$(() => {
                                                                                                                                                                                                                                                $(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ".new-card"
                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .slice(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .show();
                                                                                                                                                                                                                                                $(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ".load-more"
                                                                                                                                                                                                                                                ).click(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ".new-card:hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .slice(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .slideDown();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                );
});

var swiper = new Swiper(".mySwiperPopuler", {
                                                                                                                                                                                                                                                grabCursor: true,
                                                                                                                                                                                                                                                spaceBetween: 25,
                                                                                                                                                                                                                                                centeredSlides: true,
                                                                                                                                                                                                                                                slidesPerView: "auto",
                                                                                                                                                                                                                                                navigation: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextEl: ".swiper-button-next",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                prevEl: ".swiper-button-prev",
                                                                                                                                                                                                                                                },
});
